# test actions locally with `act` project

name: Hello World!

on:
  push:
    branches:
      - main
      # note that your "main" branch might be called main instead of master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

      - name: Print date in long format
        run: |
          date +"%A, %B %d, %Y %H:%M:%S"

      - name: print current directory
        run: |
          ls -l .
