name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies 
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: part11/full-stack-open-pokedex
        run: pnpm install  

      - name: Check style
        working-directory: part11/full-stack-open-pokedex
        run: pnpm eslint

      - name: Build project
        working-directory: part11/full-stack-open-pokedex
        run: pnpm build  

      - name: Test code
        working-directory: part11/full-stack-open-pokedex
        run: pnpm test

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: pnpm test:e2e
          start: pnpm start-prod
          wait-on: http://localhost:5000
          working-directory: part11/full-stack-open-pokedex

      # Add secrets to github repo it self
      # connect render to repo wit build and start commands, then stop auto deploy
      # also make /halth endpoint then connect it to render, if it is not runn render will not deploy it
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
