name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Move to pokedex directory
        run: |
            cd ./part11/full-stack-open-pokedex

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4


      - name: Install dependencies 
        run: pnpm install  

      - name: Check style
        run: pnpm eslint